include: package:lint/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    always_specify_types: true
    sort_constructors_first: true
    prefer_single_quotes: false
    argument_type_not_assignable: false
