name: generali
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  lint: ^1.5.3
  flutter_rating_bar: ^4.0.0

  carousel_slider: ^4.0.0
  sleek_circular_slider: ^2.0.1

  shared_preferences: ^2.0.7

  http: ^0.13.3
  json_annotation: ^1.2.0
  flutter_dotenv: ^5.0.2

  video_player: ^2.2.3

  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
