import 'package:generali/model/news.dart';

List<News> fackNewsData() {
  return <News>[
    News(
      id: '111',
      rating: 2.2,
      image: '',
      title: 'This is the First Cat Title 111',
      characteristics: 'SI',
      modality: 'online',
      status: 'No Solicitado',
      type: 'course',
      first: 'first',
      last: 'last',
      number: 0,
      totalElements: 2,
      totalPages: 3,
    ),
    News(
      id: '222',
      rating: 3.2,
      image: '',
      title: 'This is the First Cat Title 222',
      characteristics: 'SI',
      modality: 'offline',
      status: 'Solicitado',
      type: 'course',
      first: 'first',
      last: 'last',
      number: 0,
      totalElements: 2,
      totalPages: 3,
    ),
    News(
      id: '333',
      rating: 4,
      image: '',
      title: 'This is the First Cat Title 333',
      characteristics: 'SI',
      modality: 'offline',
      status: 'No Solicitado',
      type: 'course',
      first: 'first',
      last: 'last',
      number: 0,
      totalElements: 2,
      totalPages: 3,
    ),
    News(
      id: '4444',
      rating: 1,
      image: '',
      title: 'This is the First Cat Title 444',
      characteristics: 'SI',
      modality: 'online',
      status: 'No Solicitado',
      type: 'course',
      first: 'first',
      last: 'last',
      number: 0,
      totalElements: 2,
      totalPages: 3,
    ),
  ];
}
